alias: Contrôle Intelligent du Chauffe-Eau Solaire
description: >
  Contrôle du chauffe-eau basé sur la consommation et la production solaire.
  S'active lorsque la production dépasse 1800W ou pendant les heures creuses
  (21:30-23:30 et 02:30-06:30). Une fois allumé, il reste activé jusqu'à ce que
  la consommation dépasse 300W en dehors des heures creuses.
trigger:
  - platform: time_pattern
    minutes: /15
condition: []
action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: "21:30:00"
                before: "23:30:00"
              - condition: time
                after: "02:30:00"
                before: "06:30:00"
              - condition: numeric_state
                entity_id: sensor.linky_puissance_apparente_instantanee_injectee
                above: 1799
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.chauffe_eau_solaire
            data: {}
      - conditions:
          - condition: and
            conditions:
              - condition: not
                conditions:
                  - condition: time
                    after: "21:30:00"
                    before: "23:30:00"
                  - condition: time
                    after: "02:30:00"
                    before: "06:30:00"
              - condition: numeric_state
                entity_id: sensor.linky_puissance_apparente_instantanee_soutiree
                above: 300
              - condition: state
                entity_id: switch.chauffe_eau_solaire
                state: "on"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.chauffe_eau_solaire
            data: {}
mode: single
