services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - "./data/HA:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus:/run/dbus:ro"
    restart: unless-stopped
    privileged: true
    network_mode: host

  esphome:
    container_name: esphome
    image: esphome/esphome:latest
    volumes:
      - "./data/esphome_data:/config"
    restart: unless-stopped
    network_mode: host

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token $cloudflared-token
    restart: unless-stopped
    network_mode: host

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --schedule "0 0 4 * * *"
    restart: unless-stopped
    network_mode: host
  
  scrypted:
    container_name: scrypted
    image: koush/scrypted
    privileged: true
    restart: unless-stopped
    volumes:
      - "./data/scrypted:/server/volume"
    network_mode: host

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./data/matter:/data
      - /run/dbus:/run/dbus:ro
  
