version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - "./data/HA:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus:/run/dbus:ro"
    restart: unless-stopped
    privileged: true
    networks:
      - homeassistant_network
    ports:
      - 8123:8123
      - 1900:1900
      - 5350:5350
      - 5351:5351
      - 51829:51829
      - 21064:21064
      - 51827:51827
      - 21064:21064

  esphome:
      container_name: esphome
      image: esphome/esphome:latest
      volumes:
        - "./data/esphome_data:/config" 
      networks:
       - homeassistant_network
      ports:
        - "6052:6052"  
        - "6123:6123"  
      restart: unless-stopped

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token 
    restart: unless-stopped
    networks:
      - homeassistant_network


  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --schedule "0 0 4 * * *" homeassistant # Mise à jour quotidienne à 4h00
    restart: unless-stopped
    networks:
      - homeassistant_network

networks:
  homeassistant_network:
    external: true
